# Generated by Django 6.0.6 on 2026-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('device_type', models.CharField(choices=[('fan', 'Fan'), ('light', 'Light')], max_length=10)),
                ('room', models.CharField(choices=[('drawing_room', 'Drawing Room'), ('work_room_1', 'Work Room 1'), ('work_room_2', 'Work Room 2')], max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('power_draw', models.FloatField(default=0)),
                ('last_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
